[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "locator"
version = "2.7.28"
description = "locator."

requires-python = ">=3.7"
dependencies = [
    "numpy",
    "PyAutoGUI",
    "psutil",
    "requests",
    "table_helper",
    "rpaframe",
    "pywin32; sys_platform == 'win32'",
    "pythonnet; sys_platform == 'win32'",
    "uiautomation; sys_platform == 'win32'",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.setuptools]
package-dir = {"locator" = "src/locator"}   
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"] 
include = ["locator*"]

[tool.setuptools.package-data]
"locator.core.exes" = ["ie/**/*", "jab/**/*"]

