[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rpa-param-utils"
version = "1.0.8"
description = "rpa_param_utils."

requires-python = ">=3.7"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.setuptools]
package-dir = {"rpa_param_utils" = "src/rpa_param_utils"}
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]
include = ["rpa_param_utils*"]

