[project]
name = "rpa-scheduler"
version = "2.1.89"
description = "scheduler."

dynamic = ["dependencies"]
requires-python = ">=3.7"

[tool.black]
line-length = 88
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_gitignore = true

[tool.pylint.messages_control]
max-line-length = 88
good-names = ["i", "j", "k", "ex", "id", "_", "db", "pk", "ui"]
disable = [
    "C0103",  # invalid-name
    "R0903",  # too-few-public-methods
    "C0111",  # missing-docstring
]

[tool.pylint.design]
max-args = 7
max-locals = 15
max-returns = 6
max-branches = 12
max-statements = 50