[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rpa-recording"
version = "1.0.8"
description = "rpa_recording."

requires-python = ">=3.7"
dependencies = [
    "rpaframe"
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.setuptools]
package-dir = {"rpa_recording" = "src/rpa_recording"}
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]
include = ["rpa_recording*"]


