[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rpaframe"
version = "1.0.10"
description = "rpaframe."

requires-python = ">=3.7"
dependencies = [
    "loguru>=0.7"
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.setuptools]
package-dir = {"rpaframe" = "src/rpaframe"}
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]
include = ["rpaframe*"]