[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rpa-executor"
version = "1.1.96"
description = "rpa_executor."

requires-python = ">=3.7"
dependencies = [
    "websockets",
    "psutil",
    "importlib_metadata",
    "anyio",
    "requests",
    "rpa_param_utils",
    "rpaframe",
    "rpaatomic",
    "rpawebsocket",
    "rpa_recording",
    "rpatools"
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.setuptools]
package-dir = {"rpa_executor" = "src/rpa_executor"}
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]
include = ["rpa_executor*"]

