[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rpawindow"
version = "1.0.18"
description = "rpawindow."

requires-python = ">=3.7"
dependencies = [
    "rpaatomic",
    "pywin32>=306; sys_platform == 'win32'",
    "uiautomation; sys_platform == 'win32'",
    "dogtail; sys_platform == 'linux'"
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.setuptools]
package-dir = {"rpawindow" = "src/rpawindow"}
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]           
include = ["rpawindow*"]

